gui:
    authorColors:
        "Niccolas Maganeli": red 
        "*": default 
    theme:
        activeBorderColor:
            - red
            - bold

        inactiveBorderColor:
            - blue

        searchingActiveBorderColor:
            - purple
            - bold

        optionsTextColor:
            - aqua
